MACHEX_PATH: machex_dataset
NUM_WORKERS: 1
FRONTAL_ONLY: True

CHEXRAY14_ROOT: null
CHEXPERT_ROOT: null
PADCHEST_ROOT: null
MIMIC_ROOT: null
VINDRCXR_ROOT: null
BRAX_ROOT: null
RSNA_ROOT: null
OPENI_ROOT: null
SIIM_ROOT: chestx-ray/SIIM_TRAIN_TEST
OBJECTCXR_ROOT: null
VINDR_PCXR_ROOT: chestx-ray/VinDr-PCXR
BIMCV_COVID19_ROOT: chestx-ray/BIMCV-COVID19
