MACHEX_PATH: machex_dataset
NUM_WORKERS: 1
FRONTAL_ONLY: false

CHEXRAY14_ROOT: null
CHEXPERT_ROOT: null
PADCHEST_ROOT: null
MIMIC_ROOT: null
VINDRCXR_ROOT: null
BRAX_ROOT: null
RSNA_ROOT: null
OPENI_ROOT: null
SIIM_ROOT: chestx-ray/SIIM_TRAIN_TEST
OBJECTCXR_ROOT: null
